### PR TITLE
implemented requirement regarding map selection

### PR DESCRIPTION
**Pull request by olegkolner**

### CODE REVIEW

**Comment by olegkolner** [comment]
Sure, we can add the feature summary to the readme

**Comment by derpatrick** [comment]
Please remove unused imports and values:
```
[14:42:15]  dev server running: http://localhost:8100/ 

            All imports are unused. 

[14:42:17]  tslint: src/components/appicon-widget/app.ts, line: 2        L1:  import {SafeResourceUrl} from "@angular/platform-browser";

       L2:  [14:42:17]  tslint: src/pages/administration/administration.ts, line: 4 i
m[14:42:17]  tslint: src/components/appicon-widget/appicon-widget.ts, line: 31 p
or[14:42:17]  tslint: src/components/appicon-widget/appicon-widget.ts, line: 33 t
 {Output, EventEmitter} from "@angular/core";

[14:42:17]  tslint: src/components/appicon-widget/appicon-widget.ts, line: 5             All imports are unused. 


       L3:  [14:42:17]  tslint: src/components/appicon-widget/appicon-widget.ts, line: 7 
import { HttpDataProvider } from "../../providers/http-data/http-data";
       L4:  [14:42:17]  tslint: src/pages/modal-catalog/modal-catalog.ts, line: 4 i
mport { App, AppStatus } from "../../components/appicon-widget/app";

            Property 'dataProvider' is declared but never used. 

      L30:  constructor(public sanitizer: DomSanitizer,
      L31:              private dataProvider: HttpDataProvider,
      L32:              private sharedLocalStorageProvider: SharedLocalStorageProvider,

            Property 'cookieService' is declared but never used. 

      L32:            private sharedLocalStorageProvider: SharedLocalStorageProvider,
      L33:            private cookieService: CookieService) {
      L34:  console.log("Initializing App Icons...");

            'AppStatus' is declared but never used. 

       L4:  } from "@angular/core";
       L5:  import {App, AppStatus} from "./app";
       L6:  import {DomSanitizer} from "@angular/platform-browser";

            All imports are unused. 

       L6:  import {DomSanitizer} from "@angular/platform-browser";
       L7:  import {LocalStorage, SessionStorage, SharedStorage} from "ngx-store";
       L8:  import {CookieService} from "ngx-cookie";

            All imports are unused. 

       L3:  import {App, AppStatus} from "../../components/appicon-widget/app";
       L4:  import {SharedStorage} from "ngx-store";
       L5:  import {DomSanitizer} from "@angular/platform-browser";

[14:42:17]  lint finished in 2.33 s 
```

**Comment by derpatrick** [comment]
TODO's:

- [ ] A message should be displayed if no app was found at the given registry URL

**Comment by kristkat** [comment]
@derpatrick i deleted unused imports and pushed my old commits where I implemented showing error messages e.g when no data could be retrieved

**Pull request merged**
